name: Build and Release MeshAgent (Windows 64-bit)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Compilar MeshAgent
      run: |
        msbuild MeshAgent.sln /p:Configuration=Release /p:Platform=x64

    - name: Localizar Executável
      run: |
        Get-ChildItem -Path . -Filter "MeshService64.exe" -Recurse | Copy-Item -Destination "MeshService64.exe"

    - name: Criar tag e Publicar Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Build
        files: MeshService64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
